theme: jekyll-theme-minimal

title: Biosphere
description: French Institute of Bioinformatics - IFB - has set up a federation of clouds, Biosphere, which relies on interconnected IT infrastructures of some IFB’s platforms, providing distributed services to analyze life science data.

logo: https://ifb-elixirfr.github.io/biosphere/assets/img/ifb-logo.png
