theme: jekyll-theme-minimal

title: IFB-Biosphere Cloud
description: French Institute of Bioinformatics - IFB - has set up a federation of clouds, Biosphere, which relies on interconnected IT infrastructures of some IFB’s platforms, providing distributed services to analyze life science data.

logo: https://ifb-elixirfr.github.io/biosphere/img/logo-ifb.png
